// Generated by CoffeeScript 1.4.0
(function() {
  var description, link, _i, _len, _ref;

  ShadowBox.init({
    modal: true
  });

  description = null;

  $.ajax({
    url: "./description.json",
    type: "GET",
    dataType: "json",
    success: function(jData) {
      return description = JSON.parse(jData);
    },
    error: function() {
      return alert("無法取得圖片描述");
    }
  });

  _ref = $(".link");
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    link = _ref[_i];
    link.click(function() {
      var pic, _j, _len1, _ref1, _results;
      _ref1 = $(".pic");
      _results = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        pic = _ref1[_j];
        pic.setAttribute("rel", "shadowbox[" + link.text + "]");
        _results.push(pic.setAttribute("title", description[pic.getAttribute("data-pic-id")]));
      }
      return _results;
    });
  }

}).call(this);
